apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-ingress
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - path: /v1
        backend:
          serviceName: hello-app-1-service
          servicePort: http
      - path: /v2
        backend:
          serviceName: hello-app-2-service
          servicePort: http
